### ISSUE TITLE
Submit to robustbench?

### ISSUE THREAD

**Issue by hendrycks** [alinlab/consistency-adversarial#1]
This seems like a good model, and it'd be great if it was submitted to [robustbench](https://robustbench.github.io/).

**Comment by jihoontack** [comment]
Hi Dan
I really appreciate the suggestion!

I will submit our model soon. It looks interesting as our work can be involved to every benchmark evaluation in [robustbench](https://robustbench.github.io/)!

Thank again for your interest
Best,
Jihoon
